version: "3"
services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: ali
      POSTGRES_PASSWORD: ali
      POSTGRES_DB: hermes
    volumes:
      - ./data:/var/lib/postgresql/data
    # ports:
    #   - "5432:5432"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8050:8050"
    expose:
      - "8050"
    depends_on:
      - db
